heroes/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf.urls.static import static

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from mysite import settings
from heroes import views
from django.contrib.auth.views import LoginView, LogoutView
from home import views as HomeViews

app_name = 'heroes'
urlpatterns = [ 
    

    path('details/<uuid:id>', views.details, name='Avenger-details'),
    path('delete/<uuid:id>', views.delete, name='Avenger-delete'),
    path('new/', views.new, name='new'),
    path('Homepage/', HomeViews.index, name='Homepage'),
    path('', views.heroes, name='Landing'),
    
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('login/', views.loginView, name='login'),
    
    path('logout/', views.logoutView, name='logout'), 
]

home/urls.py
from django.urls import path



from home import views as HomeViews

app_name = 'home'
urlpatterns = [ 
    path('', HomeViews.index, name='HomePage'),
    path('HomePage/', HomeViews.index, name='HomePage')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from heroes import views as HeoresViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('heroes/', include('heroes.urls'), name='HeroesHome'),
    path('sqlite3reader/', include('sqlite3reader.urls'), name='sqlite3reader'),
    path('', include('home.urls'), name='HomePage'),
    path('accounts/login/', HeoresViews.loginView, name='login'),
    path("accounts/", include("accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
]

sqlite3reader/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf.urls.static import static

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from mysite import settings
from sqlite3reader import views
from django.contrib.auth.views import LoginView, LogoutView
from home import views as HomeViews

app_name = 'sqlite3reader'
urlpatterns = [
    path("", views.index, name="Landing"),
    path('Homepage/', HomeViews.index, name='Homepage'),
    path(
        "favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))
    )
]

sqlite3reader/models.py
from django.db import models

# Create your models here.
class TableNameColsAndRows:
    def __init__(self, name, cols, rows:list):
        self.name = name
        self.cols = cols
        self.rows = rows

    @staticmethod
    def getcols(name, list):
        return [nested_elem for nested_elem in list if nested_elem.name == list][0].cols

sqlite3reader/views.py
import logging
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import sqlite3
from django.contrib.auth.decorators import login_required
from sqlite3reader.models import TableNameColsAndRows

# Create your views here.
@login_required
def index(request):
    data = {}
    if "GET" == request.method:
        return render(request, "sqlite3reader/upload_sqlite3db.html", data)
	
    # if not GET, then proceed
    try:
        

        sqlite3FileName = request.FILES["sqlite3db_file"]

        # Connect to the SQLite database
        conn = sqlite3.connect(sqlite3FileName.name)

        # Create a cursor object
        cursor = conn.cursor()

        # Execute a SQL query
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table'")

        nested_list = []
        
        # Fetch all rows from the executed query
        tableNames = cursor.fetchall()
        tables =  [x[0] for x in tableNames]

        for tableName in tableNames:
            getColsQuery = f'SELECT name FROM PRAGMA_TABLE_INFO("{tableName[0]}");'
            cursor.execute(getColsQuery)
            cols = cursor.fetchall()
            cols = [x[0] for x in cols]

            cursor.execute(f'SELECT * FROM {tableName[0]};')
            rows = cursor.fetchall()
            #rows = [x[0] for x in rows]

            element1 = TableNameColsAndRows(tableName[0], cols, rows)
            nested_list.append(element1)
            print(tableName)

        cursor.close()
        # Close the connection
        conn.close()
    except Exception as e:
        logging.getLogger("error_logger").error("Unable to upload file. "+repr(e))
    return render(request, "sqlite3reader/upload_sqlite3db.html", {"tables": tables, "nested_list": nested_list})

templates/sqlite3reader/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sqlite3 DB Reader</title>
  <link rel="icon" title="logo" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>
  <div class="container">
    <h2>Read Sqlite3 DB</h2>
    {% if user.is_authenticated %}
    <a href="{% url 'heroes:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'heroes:login' %}">Login</a>
    {% endif %}
    <a href="{% url 'heroes:Landing'  %}">Avengers</a>
    <a href="{% url 'sqlite3reader:Homepage'  %}">Home</a>
    
    {% block content %} {% endblock content %}
  </div>
</body>

</html>

templates/sqlite3reader/upload_sqlite3db.html
{% extends "sqlite3reader/base.html" %}
{% load static %}
{% block content %}

<form method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="name" class="col-md-3 col-sm-3 col-xs-12 control-label">Select Sqlite3 DB File: </label>
        <div class="col-md-8">
            <input type="file" name="sqlite3db_file" id="sqlite3db_file" required="True" class="form-control">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-3 col-sm-3 col-xs-12 col-md-offset-3" style="margin-bottom:10px;">
            <button class="btn btn-primary"> <span class="glyphicon glyphicon-upload"
                    style="margin-right:5px;"></span>Upload </button>
        </div>
    </div>
</form>
<h3>Tables in the Sqlite3 DB</h3>
<table class="table-striped">
    <thead>
        <th>Table Name</th>
        <th>Data</th>
    </thead>
    <tbody>
        {% for item in nested_list %}

        <tr>

            <td>{{item.name}}</td>
            <td>
                <table class="table-striped">
                    <thead>
                        <tr>
                            <th scope="col">#</th>
                            {%for i in item.cols %}
                            <th scope="col">{{i}}</th>
                            {%endfor%}
                        </tr>
                    </thead>
                    {% if item.rows|length == 0 %}
                    <p>No rows</p>
                    {% else %}
                    <tbody>
                        {%for i in item.rows %}

                        <tr>
                            <th scope="row">{{loop.index}}</th>
                            {%for k in i%}
                            <td>{{k}}</td>
                            {%endfor%}
                        </tr>

                        {%endfor%}


                    </tbody>
                    {% endif %}
                </table>
            </td>


        </tr>
        {% endfor %}

    </tbody>
</table>

{% endblock content %}