heroes/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf.urls.static import static

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from mysite import settings
from heroes import views
from django.contrib.auth.views import LoginView, LogoutView
from home import views as HomeViews

app_name = 'heroes'
urlpatterns = [ 
    

    path('details/<uuid:id>', views.details, name='Avenger-details'),
    path('delete/<uuid:id>', views.delete, name='Avenger-delete'),
    path('new/', views.new, name='new'),
    path('Homepage/', HomeViews.index, name='Homepage'),
    path('', views.heroes, name='Landing'),
    
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    path('login/', views.loginView, name='login'),
    
    path('logout/', views.logoutView, name='logout'), 
]

home/urls.py
from django.urls import path



from home import views as HomeViews

app_name = 'home'
urlpatterns = [ 
    path('', HomeViews.index, name='HomePage'),
    path('HomePage/', HomeViews.index, name='HomePage')
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

from heroes import views as HeoresViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('heroes/', include('heroes.urls'), name='HeroesHome'),
    path('sqlite3reader/', include('sqlite3reader.urls'), name='sqlite3reader'),
    path('', include('home.urls'), name='HomePage'),
    path('accounts/login/', HeoresViews.loginView, name='login'),
    path("accounts/", include("accounts.urls")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
]

sqlite3reader/urls.py
from django import urls
from django.contrib import admin
from django.urls import include, path, re_path

from django.conf.urls.static import static

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

from mysite import settings
from sqlite3reader import views
from django.contrib.auth.views import LoginView, LogoutView
from home import views as HomeViews

app_name = 'sqlite3reader'
urlpatterns = [
    path("", views.index, name="Landing"),
    path('Homepage/', HomeViews.index, name='Homepage'),
    path(
        "favicon.ico", RedirectView.as_view(url=staticfiles_storage.url("favicon.ico"))
    )
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
import logging
from django.shortcuts import render

logger = logging.getLogger(__name__)

def index(request):
    return render(request, "homepage/homepage.html", {})

templates/main_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Django</title>
  <link rel="icon" title="logo" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
</head>

<body>
  <div class="container">
    <h2>Django</h2>
    {% if user.is_authenticated %}
    <p><a href="{% url 'password_change' %}">Password Change</a></p>
    <a href="{% url 'heroes:logout'  %}">Logout</a>
    {% else %}
    <p><a href="{% url 'password_reset' %}">Password Reset</a></p>
    <a href="{% url 'heroes:login'  %}">LogIn</a>
    {% endif %}
    <a href="{% url 'heroes:Homepage'  %}">Home</a>
    <a href="{% url 'sqlite3reader:Landing'  %}">Sqlite3 Reader</a>

    {% block content %} {% endblock content %}
  </div>
</body>

</html>

templates/main_app/delete.html
{% extends "./base.html" %}
{% load static %}
{% block content %}



<body>
    <script>
        $(document).ready(function () {
            $("#bigAvengerName").text('{{ myavenger.name }}')
            if ("null" === '{{form.data.disable_save}}') {
                $("#submitButton").removeAttr("disabled")
            }

            $("#avenger_name").change(function () {


                $("#bigAvengerName").text($("#avenger_name").val())
            })

            $("#submitButton").click(function (e) {


                var deleteConfirmed = confirm("Are you sure you would like to delete this avenger?")

                if (!deleteConfirmed) {
                    e.preventDefault();
                    console.log("Delete canceled")
                }
                else{
                    console.log("Delete Confirmed")
                    $("#deleteForm").submit();
                }
            })
        });
    </script>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4">
                <h6>Delete</h6>
                <h6 id="bigAvengerName"></h6>
                <h5 class="display-4 text-danger">{{ form.data.error }}</h4>
            </div>
            <div class="col-md-8">
                <form id="deleteForm" method="POST" class="p-3 border rounded shadow-sm bg-light">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6">
                            <label for="avenger_name" class="form-label">Avenger Name</label>
                            <input type="text" id="avenger_name" value="{{form.data.avenger_name}}" class="form-control"
                                required="required" readonly="readonly" name="avenger_name">
                        </div>
                        <div class="col-md-6">
                            <label for="avenger_id" class="form-label">Avenger ID</label>
                            <input type="text" id="avenger_id" readonly="readonly" class="form-control"
                                value="{{form.data.avenger_id}}" name="avenger_id">
                        </div>
                    </div>

                    <button id="submitButton" type="button" disabled="{{form.data.disable_save}}"
                        class="btn btn-danger mt-3">Delete</button>
                    <p class="text-danger">{{ form.data.hint_text }}</p>
                    {% if form.data.disable_save == "disabled" %}
                    <a class="btn btn-primary" href="{% url 'heroes:new'  %}">Add a New Avenger Instead</a>
                    {% endif %}
                </form>

                <p class="mt-3 text-info">
                    Back to <a class="btn btn-primary" href="{% url 'heroes:Landing' %}">List of Avengers</a>
                </p>
            </div>
        </div>
    </div>
</body>


{% endblock content %}

templates/main_app/error.html
{% extends "./base.html" %}

{% block content %}
<div class="col-md-6 col-auto">
    <div class="card">
        <div class="card-header text-danger">
            <pre>{{errors}}</pre>
            <p>{{errors}}</p>
            
        </div>        
    </div>
</div>
{% endblock content %}

templates/main_app/home.html
{% extends "./base.html" %}

{% block content %}
<div class="card">
    <div class="card-header">
        My Own Avengers
    </div>
    <div class="row">
        <div class="col-md-4">
            <p class="text-info"><a class="btn btn-primary" href="{% url 'heroes:new'  %}">Add a New Avenger</a></p>
        </div>
        <div class="col-md-8">
            <table class="table-striped">
                <thead>
                    <th>Name</th>
                    <th></th>
                </thead>
                <tbody>
                    {% for avenger in avengers %}
                    <tr>

                        <td><a href="{% url 'heroes:Avenger-details' avenger.id %}">{{avenger.name}}</a><a
                                style="visibility:hidden" href="{% url 'heroes:Avenger-details' avenger.id %}">{{
                                avenger.name }}</a></td>
                        <td><a class="btn btn-danger" href="{% url 'heroes:Avenger-delete' avenger.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/main_app/login.html
{% extends "./base.html" %}
{% load static %}
{% block content %}

<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">Login</button>
            </form>
        </div>
    </div>
</div>


{% endblock content %}

templates/main_app/logoutsuccess.html
{% extends "./base.html" %}

{% block content %}
<div class="col-md-6 col-auto">
    <div class="card">
        <div class="card-header text-info">
            Logout Was successful.
        </div>        
    </div>
</div>
{% endblock content %}

templates/main_app/name.html
{% extends "./base.html" %}
{% load static %}
{% block content %}



<body>
    <script>
        $(document).ready(function () {
            $("#bigAvengerName").text('{{ myavenger.name }}')
            if ("null" === '{{form.data.disable_save}}') {
                $("#submitButton").removeAttr("disabled")
            }

            $("#avenger_name").change(function () {
               
                
                $("#bigAvengerName").text($("#avenger_name").val())
            })
        });
    </script>

    <div class="container mt-4">
        <div class="row">
            <div class="col-md-4">
                <h6 id="bigAvengerName"></h6>
                <h5 class="display-4 text-danger">{{ form.data.error }}</h4>
            </div>
            <div class="col-md-8">
                <form method="post" class="p-3 border rounded shadow-sm bg-light">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-md-6">
                            <label for="avenger_name" class="form-label">Avenger Name</label>
                            <input type="text" id="avenger_name" value="{{form.data.avenger_name}}" class="form-control"
                                required="required" name="avenger_name">
                        </div>
                        <div class="col-md-6">
                            <label for="avenger_id" class="form-label">Avenger ID</label>
                            <input type="text" id="avenger_id" readonly="readonly" class="form-control"
                                value="{{form.data.avenger_id}}" name="avenger_id">
                        </div>
                    </div>

                    <button id="submitButton" type="submit" disabled="{{form.data.disable_save}}"
                        class="btn btn-success mt-3">Save</button>
                    <p class="text-danger">{{ form.data.hint_text }}</p>
                    {% if form.data.disable_save == "disabled" %}
                    <a class="btn btn-primary" href="{% url 'heroes:new'  %}">Add a New Avenger Instead</a>
                    {% endif %}
                </form>

                <p class="mt-3 text-info">
                    Back to <a class="btn btn-primary" href="{% url 'heroes:Landing' %}">List of Avengers</a>
                </p>
            </div>
        </div>
    </div>
</body>


{% endblock content %}